code --install-extension Angular.ng-template
code --install-extension bradlc.vscode-tailwindcss
code --install-extension dracula-theme.theme-dracula
code --install-extension esbenp.prettier-vscode
code --install-extension GraphQL.vscode-graphql
code --install-extension GraphQL.vscode-graphql-execution
code --install-extension GraphQL.vscode-graphql-syntax
code --install-extension PKief.material-icon-theme
code --install-extension svelte.svelte-vscode
